### ISSUE TITLE
Will there be an 1.17 update / auth bug with mincraft 1.17.1

### ISSUE THREAD

**Issue by Pretoreaner** [eylexlive/Discord2FA#4]
I've a problem with version 1.17.1 and Discord2FA 3.5
once i recive the auth code in Discord and write /auth <authcode> it says ingame authenticated but i can't move anyway untill ei relog and then it says already authenticated and i can move normaly

**Comment by AustinPoonia** [comment]
Having this issue too on 1.18.1 , if i can figure it out ill create a branch on the project until it gets adopred into the main branch.

The stack trace is:
[06:56:39] [Server thread/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: EntityDismountEvent cannot be triggered asynchronously from another thread.
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[06:56:39] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: EntityDismountEvent cannot be triggered asynchronously from another thread.
[06:56:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.removePassenger(Entity.java:2255)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.bt(Entity.java:2166)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.bt(EntityHuman.java:1078)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.p(Entity.java:2172)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.p(EntityLiving.java:3274)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.p(EntityPlayer.java:1298)
[06:56:39] [Server thread/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.b(Entity.java:3690)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.a(Entity.java:448)
[06:56:39] [Server thread/WARN]: 	at net.minecraft.world.entity.Entity.ah(Entity.java:430)
[06:56:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.remove(CraftEntity.java:602)
[06:56:39] [Server thread/WARN]: 	at io.github.eylexlive.discord2fa.manager.Discord2FAManager.unSitPlayer(Discord2FAManager.java:516)
[06:56:39] [Server thread/WARN]: 	at io.github.eylexlive.discord2fa.manager.Discord2FAManager.completeAuth(Discord2FAManager.java:166)
[06:56:39] [Server thread/WARN]: 	at io.github.eylexlive.discord2fa.provider.YamlProvider.authPlayer(YamlProvider.java:66)
[06:56:39] [Server thread/WARN]: 	at io.github.eylexlive.discord2fa.command.AuthCommand.lambda$onCommand$0(AuthCommand.java:96)
[06:56:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
