### ISSUE TITLE
Help. Error.

### ISSUE THREAD

**Issue by TheKi3End** [eylexlive/Discord2FA#5]
[12:42:56] [Server thread/INFO]: Ki3End issued server command: /auth 369592
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: EntityDismountEvent may only be triggered synchronously.
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: java.lang.IllegalStateException: EntityDismountEvent may only be triggered synchronously.
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.Entity.removePassenger(Entity.java:2678)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:2579)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.EntityLiving.stopRiding(EntityLiving.java:3502)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.stopRiding(EntityHuman.java:1164)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.server.level.EntityPlayer.stopRiding(EntityPlayer.java:1439)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.server.level.EntityPlayer.stopRiding(EntityPlayer.java:1434)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4253)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.Entity.a(Entity.java:628)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.minecraft.world.entity.Entity.die(Entity.java:610)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.remove(CraftEntity.java:669)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.manager.Discord2FAManager.unSitPlayer(Discord2FAManager.java:516)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.manager.Discord2FAManager.completeAuth(Discord2FAManager.java:166)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.provider.YamlProvider.authPlayer(YamlProvider.java:66)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.command.AuthCommand.lambda$onCommand$0(AuthCommand.java:96)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[12:42:56] [ForkJoinPool.commonPool-worker-3/WARN]: 	... 6 more

**Comment by TheKi3End** [comment]
[12:56:30 WARN]: 1153640 [JDA MainWS-ReadThread] ERROR io.github.eylexlive.discord2fa.depend.jda.api.JDA - One of the EventListeners had an uncaught exception
[12:56:30 WARN]: java.lang.NoClassDefFoundError: io/github/eylexlive/discord2fa/depend/jda/api/events/RawGatewayEvent
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:375)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.internal.requests.WebSocketClient.handleDisconnect(WebSocketClient.java:497)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:431)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.WebSocket.finish(WebSocket.java:3758)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3724)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3691)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.ReadingThread.runMain(ReadingThread.java:80)
[12:56:30 WARN]:        at Discord2FA.v3.5 (1).jar//io.github.eylexlive.discord2fa.depend.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by arturek1666** [comment]
I am getting a bit different error will post is seperate.
